# -*- coding: utf-8 -*-
"""mall_customer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jeOAmgGfBj2PJQ_YqPXEZMFDAW6R-h97
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

data=pd.read_csv('/content/mall_customer.csv')
data.head()

X=data[["Annual Income (k$)","Spending Score (1-100)"]]

model=KMeans(n_clusters=5,random_state=42)
data["Clusters"]=model.fit_predict(X)

print(data.head())

plt.scatter(data["Annual Income (k$)"],data["Spending Score (1-100)"],c=data["Clusters"])
plt.show()